GestaoFinancaPessoal/GestaoFinancaPessoal/Controllers/ContaController.cs
using GestaoFinancaPessoal.DAO;
using GestaoFinancaPessoal.Data;
using GestaoFinancaPessoal.Models;
using GestaoFinancaPessoal.Uteis.Exception.ModelErrorException;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace GestaoFinancaPessoal.Controllers
{
    public class ContaController : Controller
    {
        public ContaController(ApplicationDbContext Contexto, IHttpContextAccessor contextAcessor) : base(Contexto, contextAcessor)
        {
        }


        // GET: Conta
        public ActionResult Index()
        {
            var contaDAO = this.DAO.NewDAO<ContaDAO>();
            return View(contaDAO.ListContaView());
        }

        // GET: Conta/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Conta/Create
        public ActionResult Create()
        {
            return View(new Conta { Saldo = 0 });
        }

        // POST: Conta/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Conta conta)
        {
            ViewBag.Salvo = false;
            try
            {
                if (ModelState.IsValid)
                {
                    var contaDAO = this.DAO.NewDAO<ContaDAO>();

                    conta.DataAtualizacao = DateTime.Now;
                    contaDAO.Add(conta);
                    contaDAO.SaveChanges();
                    ViewBag.Salvo = true;
                }
                else
                {
                    return View(conta);
                }

                this.ViewBag.Salvo = true;
                return View(conta);
            }
            catch (ModelErrorException e)
            {
                this.AddModelError(e);
                return View(conta);
            }

        }

        // GET: Conta/Edit/5
        public ActionResult Edit(int id)
        {
            var contaDAO = this.DAO.NewDAO<ContaDAO>();
            var conta = contaDAO.getById(id);

            return View(conta);
        }

        // POST: Conta/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Conta conta)
        {
            try
            {
                ViewBag.Alterado = false;

                if (ModelState.IsValid)
                {
                    var contaDAO = this.DAO.NewDAO<ContaDAO>();

                    conta.Id = id;
                    conta.DataAtualizacao = DateTime.Now;
                    contaDAO.Update(conta);
                    contaDAO.SaveChanges();
                    ViewBag.Alterado = true;
                }
                else
                {
                    return View(conta);
                }

                return View(conta);
            }
            catch (ModelErrorException e)
            {
                this.AddModelError(e);
                return View(conta);
            }

        }

        // GET: Conta/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                ViewBag.Excluido = false;

                var contaDAO = this.DAO.NewDAO<ContaDAO>();
                Conta conta = contaDAO.getById(id);

                contaDAO.Remove(conta);
                contaDAO.SaveChanges();
                ViewBag.Excluido = true;
                return View("index", contaDAO.ListContaView());

            }
            catch (ModelErrorException e)
            {
                this.AddModelError(e);
            }
            return View();
        }

        public ActionResult Suspender(int id)
        {
            try
            {
                ViewBag.Suspenso = false;

                var contaDAO = this.DAO.NewDAO<ContaDAO>();
                Conta conta = contaDAO.getById(id);
                conta.IsSuspensa = true;
                contaDAO.Update(conta);
                contaDAO.SaveChanges();
                ViewBag.Suspenso = true;
                return View("index", contaDAO.ListContaView());

            }
            catch (ModelErrorException e)
            {
                this.AddModelError(e);
            }
            return View();
        }

        // POST: Conta/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IList<Conta> ListConta()
        {
            var contaDAO = this.DAO.NewDAO<ContaDAO>();
            return contaDAO.List();
        }
    }
}

GestaoFinancaPessoal/GestaoFinancaPessoal/Views/Shared/_LancamentoButton.cshtml
<div class="row" >
    <div class="fixed-bottom mb-5 mr-5 ml-5" botoes>
        <div class=" float-right col-12  col-md-1" LancamentoDIV ondblclick="MoverBotao()" onclick="ExibirOcultarAtalhos()">
            <a class="btn btn-primary-outline float-right float-sm-right">
                <div class="stat-widget-one">
                    <div class="stat-icon dib">
                        <i class="material-icons color-primary border-primary" IconeBtn>add</i>
                    </div>
                </div>
            </a>
        </div>

        <div class=" float-right col-12  col-md-1" Lancamento style="display: none;">
            <a asp-action="Receita" asp-controller="Lancamento" class="btn btn-primary-outline float-right float-sm-right ">
                <div class="stat-widget-one">
                    <div class="stat-icon dib">
                        <i class="material-icons color-success border-success">trending_up</i>
                    </div>
                </div>
            </a>
        </div>

        <div class=" float-right col-12  col-md-1" Lancamento style="display: none;">
            <a asp-action="Create" asp-controller="Lancamento" class="btn btn-primary-outline float-right float-sm-right ">
                <div class="stat-widget-one">
                    <div class="stat-icon dib">
                        <i class="material-icons color-danger border-danger">trending_down</i>
                    </div>
                </div>
            </a>
        </div>

        <div class=" float-right col-12  col-md-1" Lancamento style="display: none;">
            <a asp-action="Transferencia" asp-controller="Lancamento" class="btn btn-primary-outline float-right float-sm-right ">
                <div class="stat-widget-one">
                    <div class="stat-icon dib">
                        <i class="material-icons color-info border-info">autorenew</i>
                    </div>
                </div>
            </a>
        </div>

    </div>
</div>


<script src="~/js/Lancamento/Index.js">
</script>

GestaoFinancaPessoal/GestaoFinancaPessoal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestaoFinacaPessoal</title>
    <link rel="manifest" href="~/manifest.json">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <div class=" @(ViewBag.SemContainer != null && ViewBag.SemContainer.ToLower() == "sim" ? "container-fluid" : "container" ) " id="container">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>
        //warning error success info
        var salvo = '@ViewBag.Salvo';
        var excluido = '@ViewBag.Excluido';
        var alterado = '@ViewBag.Alterado';
        var suspenso = '@ViewBag.Suspenso';
        var erro = '@ViewBag.Erro';

        var semContainer = '@ViewBag.SemContainer';

        if (salvo == 'True') {
            swal("Salvo com sucesso!", "", "success")
                .then((value) => {
                    window.location.href = window.location.href + "/../";
                });
        }

        if (excluido == 'True') {
            swal("Excluido com sucesso!", "", "success")
            .then((value) => {
                    window.location.href = window.location.href + "/../../";
                });
        }

        if (suspenso == 'True') {
            swal("Suspensa com sucesso!", "", "success");
        }

        if (erro != '') {
            swal("Erro!", decodeURIComponent(escape(erro)) , "error");
        }

        if (alterado == 'True') {
            swal("Alterado com sucesso!", "", "success")
                .then((value) => {
                    var caminho = window.location.href.split("/");

                    if (isNaN(caminho[caminho.length - 1])) {
                        window.location.href = window.location.href + "/../";
                    } else {
                        window.location.href = window.location.href + "/../../";
                    }
            });
        }
    </script>



    @RenderSection("Scripts", required: false)
    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }


    @*<script>
            if ('serviceWorker' in navigator) {
                navigator.serviceWorker.register('/sw.js')
                    .then(function () {
                        console.log('service worker registered');
                    })
                    .catch(function () {
                        console.warn('service worker failed');
                    });
            }
        </script>
        <script src="~/install.js"></script>*@


    <script>
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('/sw.js')
                .then(function () {
                    console.log('service worker registered');
                })
                .catch(function () {
                    console.warn('service worker failed');
                });
        }
    </script>

</body>
</html>

GestaoFinancaPessoal/GestaoFinancaPessoal/Views/Shared/_ModalCadastro.cshtml
<div class="modal fade bd-example-modal-xl" id="Model" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <iframe style="width: 100%;height: 77vh;position: relative;" id="iFrameModel" src="@Url.Action("Create", "Conta")" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>



<script>

    $("#Model").on('hidden.bs.modal', function (e) {
        debugger;
        // do something...
        let token = $("[name=__RequestVerificationToken]").val();
        let headers = {};
        headers["RequestVerificationToken"] = token;

        //o AJAX precissa de algum atributos para funcionar
        //URL           : o Endereco do metodo (controller/metodo)
        //TYPE          : Tipo de requisicao HTTP
        //contentType   : formato dos dados JSON
        //DATA          : os Dados
        $.ajax({
            url: destino,
            type: "POST",
            contentType: "application/json",
            data: "",
            headers: headers                //token de validacao para a controller
        }).done(function (response) {
            debugger;

            Response(response);
        }
        );
    })
</script>